name: Cypress Tests

on:
  push:
    branches:
      - wakhare11  # Trigger tests on push to the main branch
  pull_request:
    branches:
      - wakhare11  # Trigger on PRs to main
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # Set your Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress tests
        run: |
          npx cypress run --browser chrome
